apiVersion: v1
metadata:
  name: {{ include "imagePullSecret.name" . }}
kind: Secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret.dockerconfigjson" . }}
