{{- if and .Values.mongodb.enabled .Values.mongodb.migrate.enabled -}}
apiVersion: batch/v1
kind: Job
  metadata:
    name: {{ include "mongodb.name" . }}-migreate
  labels:
    db/name: mongodb
spec:
  containers:
    - name: migrate
      image: {{ include "mongodb.migrate.image" . }}
      imagePullPolicy: {{ .Values.cluster.imagePullPolicy }}
      command:
        - /migrate-backend
      args:
        - --mongo-endpoint={{ include "mongodb.host" . }}:{{ include "mongodb.port" . }}
        - --mongo-password={{ include "mongodb.password" . }}
        - --mongo-username={{ include "mongodb.username" . }}
  restartPolicy: Never
  imagePullSecrets:
    {{ include "imagePullSecret.dockerconfigjson" . | indent 8 }}

{{- end -}}